ahv/ahv_module_blk.o: ahv/ahv_module_blk.c ahv/ahv.h ahv/../common/cc.h \
  ahv/../common/elf_structs.h ahv/../common/mft.h \
  /Users/user/_/tankie/vendor/solo5/include/mft_abi.h ahv/ahv_abi.h \
  ahv/../common/block_attach.h \
  /Users/user/_/tankie/vendor/solo5/tenders/common/mft.h \
  /Users/user/_/tankie/vendor/solo5/include/solo5.h
ahv/ahv.h:
ahv/../common/cc.h:
ahv/../common/elf_structs.h:
ahv/../common/mft.h:
/Users/user/_/tankie/vendor/solo5/include/mft_abi.h:
ahv/ahv_abi.h:
ahv/../common/block_attach.h:
/Users/user/_/tankie/vendor/solo5/tenders/common/mft.h:
/Users/user/_/tankie/vendor/solo5/include/solo5.h:
